### ISSUE TITLE
In 'Schedule' view, month and day turn white and are barely visible with 'Light Overlay' on light background image

### ISSUE THREAD

**Issue by TechFlowers409** [padster/CalendarThemeExtension#10]
This is on a background image that is mostly white.  Dark overlay does turn that particular area to a black font and does make it visible but it also turns everything else grey and changes the entire aesthetic.  Please fix this tiny detail, maybe just use a medium grey color for that font or something because this extension is AMAZING and I love it otherwise!  Thanks for making such an awesome addition to something we use everyday.

**Comment by padster** [comment]
Good catch - I've submitted a fix, your extension should update top have visible month and day text over the next day or two, if it's still broken after that do let me know; and I'm glad you're liking it!
