### ISSUE TITLE
White on White Side Calendar

### ISSUE THREAD

**Issue by tpisfil** [padster/CalendarThemeExtension#15]
Any image of color that gets put, regardless of whether it is a light or dark overlay, makes the circles on the date white on white and therefore you can't see anything anymore. I've attached a picture so you can better understand what I mean. Thank you! 
<img width="465" alt="Screenshot 2023-11-30 at 13 00 31" src="https://github.com/padster/CalendarThemeExtension/assets/82001337/70cdd9c1-5e79-4e81-82cc-d7e842415cf9">

**Comment by katonotkayto** [comment]
I am seeing the same white circles today 11/30. I switched from dark overlay to light overlay and I can see the numbers in the white circles for now.
![image](https://github.com/padster/CalendarThemeExtension/assets/152558017/95749a80-4933-4577-b24e-a5f44eb389c3)

**Comment by tpisfil** [comment]
Appreciate everyone looking into this! I'll keep playing with the settings tonight to see if I can get it. Love this extension btw!!

**Comment by alexander-seidl** [comment]
> Any image of color that gets put, regardless of whether it is a light or dark overlay, makes the circles on the date white on white and therefore you can't see anything anymore. I've attached a picture so you can better understand what I mean. Thank you! <img alt="Screenshot 2023-11-30 at 13 00 31" width="465" src="https://private-user-images.githubusercontent.com/82001337/287026971-70cdd9c1-5e79-4e81-82cc-d7e842415cf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE0MTQ0NzAsIm5iZiI6MTcwMTQxNDE3MCwicGF0aCI6Ii84MjAwMTMzNy8yODcwMjY5NzEtNzBjZGQ5YzEtNWU3OS00ZTgxLTgyY2MtZDdlODQyNDE1Y2Y5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAxVDA3MDI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MDEwZGJhYzU3MDMxODFlMGI2YjY3NzFkZjI1OTlhNmZhZmQzZTM2ZmEwMzYxZWI2ZjhhMDFhYmM0ZTZmZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FBoT6SPz04lDb1w4Q452w3pidHDHbTCKm92YkKscl9E">

Same problem here

**Comment by padster** [comment]
Hey everyone - thanks for your patience, the main problem has been resolved, are people still seeing the issue?
The solution was not ideal, so I will also look into optimizing it (e.g. you lose the blue 'today' indicator)

**Comment by alexander-seidl** [comment]
Works for me now with "Dark Overlay" Thank you very much :)
![image](https://github.com/padster/CalendarThemeExtension/assets/180246/553b2323-780c-44a4-9c63-fde0130a605e)

**Comment by katonotkayto** [comment]
Hello, thank you. I can see the numbers now when I switch back to dark overlay. 
![image](https://github.com/padster/CalendarThemeExtension/assets/152558017/fef24a7f-696a-4283-8b65-ef3b4176baf4)
