### ISSUE TITLE
Extension asks for email address

### ISSUE THREAD

**Issue by flemesre** [padster/CalendarThemeExtension#17]
After restarting Chrome today, the extension was disabled automatically due to a new permission requirement. It now asks for my email address:

![image](https://github.com/padster/CalendarThemeExtension/assets/7189654/62496877-92d8-48a6-9c26-8465cb167331)

Is this intended behaviour? A quick look through the recent commits didn't show anything, and the [manifest.json](https://github.com/padster/CalendarThemeExtension/blob/dc1162de2d11b2d168b29d91c323d862181fdbc9/manifest.json#L22) file isn't showing an email permission requirement.

**Comment by padster** [comment]
Hi @flemesre - thanks for flagging; that's intended behaviour, I just updated to a new 2.0 version which has the new feature of allowing people to purchase themes. This requires access to your email address, for verifying that you have access to the theme.

Unfortunately based on how chrome extensions work, I can't request it only when using themes, and have to do it at the start for everyone. 

This update includes a new website for the extension, for more details, see: https://calendar.useit.today/legal
I should be pushing a new version soon after I deal with a few bugs in the current update.

**Comment by padster** [comment]
Fix submitted to google, now just waiting for them to accept it.
I've also merged the changes to this repository, so the manifest.json update should be visible

**Comment by flemesre** [comment]
Great, thank you. I was worried because the manifest on this repository hadn't been updated and the https://useit.today domain that the Chrome Store page links to (without the calendar prefix) leads to a connection timeout.
