### ISSUE TITLE
The Monthly View is only white and no longer shows the background

### ISSUE THREAD

**Issue by Userename11** [padster/CalendarThemeExtension#18]
I've seen some other reviews and apparently it's something to do with chrome updating but if anyone can help that'd be great thank you!!!

![gcal glitch](https://github.com/padster/CalendarThemeExtension/assets/129642052/817033c1-e6ac-4eff-980c-f3ed387bcfea)

**Comment by loresmarketing** [comment]
I have the same issue. 😩

**Comment by ThalmorBiznitch** [comment]
I'm also having the same problem this morning.

**Comment by Matman747** [comment]
I also have the same problem with a 2-week view

**Comment by padster** [comment]
Thanks for flagging this and providing screenshots, I've been able to track down the issue and the fix shouldn't take long.
There'll be a some while Google review the changes and gradually roll it out to everyone, but hopefully within a day everyone will have their backgrounds visible again!

**Comment by clach04** [comment]
> I also have the same problem with a 2-week view. It started this morning.

I didn't even know this was an option! Thank you, I now have a 2-week option too :-)

http://googlesystem.blogspot.com/2008/02/custom-views-in-google-calendar.html

As is implied with other reports; the day, weekly, and schedule views seem fine.

**Comment by padster** [comment]
Okay, fix was submitted with https://github.com/padster/CalendarThemeExtension/commit/410136a7cb5d15765c43fe56ae3d610e66aa8720 
Now we're at the mercy of Google reviewing it, but for these types of changes that are mostly styling, they're fairly fast. 
If it's still broken a day from now, let me know and I'll look into it more, but I imagine it'll be fairly quick.

**Comment by Userename11** [comment]
thank you so much for the prompt help!
