### ISSUE TITLE
Can't move events that are shorter than an hour?

### ISSUE THREAD

**Issue by dorakathryn** [padster/CalendarThemeExtension#2]
Was having no problem moving around events by clicking and dragging them, and then I applied a new background color and now I can't move any of my shorter events, only extend them.

**Comment by padster** [comment]
I'm sorry it broke - I can see it's happening for me too, so was able to submit a fix. Once it passes google review (usually within a few days, if not sooner), it will return to having a much smaller target at the bottom to extend - the rest will let you drag.

Thanks for reporting this quickly too - it appears google did a few other [updates to calendar](https://workspaceupdates.googleblog.com/2022/02/manage-overdue-tasks-in-google-calendar.html), so some other things were broken (e.g. the new right-click menus, and some participant lists), this update should make those more readable as well.
