### ISSUE TITLE
White Borders around times/timegrid even in Dark mode

### ISSUE THREAD

**Issue by cdcollins13** [padster/CalendarThemeExtension#21]
<img width="913" alt="Screenshot 2024-02-26 at 2 02 45 PM" src="https://github.com/padster/CalendarThemeExtension/assets/161372049/5a2d50c1-3a8e-4806-9264-f302a0c9794d">

**Comment by Traco526** [comment]
I also have this issue and I hate it. It's driving me bonkers.
