### ISSUE TITLE
Picture doesn't show up on calendar instead a white box does

### ISSUE THREAD

**Issue by mmbrodeur** [padster/CalendarThemeExtension#22]
![Screenshot_5-3-2024_13487_calendar google com](https://github.com/padster/CalendarThemeExtension/assets/162378266/b57cd3f8-205c-4bcf-a590-85311cbe6250)

**Comment by padster** [comment]
Thanks for reporting - a fix has been submitted to google, hopefully they accept it soon and get the update to everyone!

https://github.com/padster/CalendarThemeExtension/commit/ef9a6500f23aa91b97062e3dde197582e4dd4ded

**Comment by nadawassef** [comment]
oh same issue as me - sorry i will delete my issue and follow this one

**Comment by alexander-seidl** [comment]
As a side note: This is only an issue für the custom and week view.
The day und month view work as expected.

**Comment by okharlip** [comment]
Adding to above - Day view is NOT working as expected for me:

![Screenshot](https://github.com/padster/CalendarThemeExtension/assets/21342950/07c7e9d1-8214-4c8b-93fd-f8ce60bc0632)

**Comment by alexander-seidl** [comment]
For me, it is working as expected
![image](https://github.com/padster/CalendarThemeExtension/assets/180246/68042c77-1f07-4cec-883f-7173da3d2e19)

**Comment by nadawassef** [comment]
Day is working for me as well but i dont use day at all, i need week view
hopefully this gets fixed soon

**Comment by okharlip** [comment]
For me - Day, Week and 7 days views are **NOT** working.
Month, Year and Schedule views are working fine. But I have so many meetings, month view is too crowded for me.

**Comment by Juliabriner** [comment]
Same issue here. Week and 4 days is NOT working day, year, and schedule are. Hope this gets fixed soon!!

**Comment by padster** [comment]
That's great - I can confirm that Google finally accepted the fix, and the new version should be rolled out to everyone over the next day. If it still persists after that, check at chrome://extensions that you're on the new version (2.0.8), it may take some for your browser to pick up the new version. In theory you can uninstall and reinstall to force it to upgrade, but that will override any settings you have.

**Comment by padster** [comment]
Marking as Done, will reopen if there are still issues within a few days, and separately I have a few ideas of how to reduce the risk of Google breaking things in the future.
