### ISSUE TITLE
background disappeared when creating an event 

### ISSUE THREAD

**Issue by nadawassef** [padster/CalendarThemeExtension#27]
![Cursor_and_Canva_-_Calendar_-_Event_details](https://github.com/padster/CalendarThemeExtension/assets/162406757/6da675e7-1d49-4635-8277-ec734c4bf2ef)

it seems like we have lost the background when creating an event 

please if you can fix it that would be amazing

--

**Comment by padster** [comment]
Thanks for reporting! I should be able to have a fix ready tomorrow

**Comment by nadawassef** [comment]
thank you sooo much - much appreciated

**Comment by nadawassef** [comment]
can i please check if a fix for this is coming soon?

**Comment by nadawassef** [comment]
![image](https://github.com/padster/CalendarThemeExtension/assets/162406757/5721e03a-c4f8-4387-af1f-9f826a7c5655)
i have also noticed there is a white box around where the timezone part is - see attached screenshot

**Comment by padster** [comment]
Hopefully the event background issue is fixed - there's another with event titles (see https://github.com/padster/CalendarThemeExtension/issues/28) which should be fixed soon too, but I can look into the white box issue - I don't use the timezone feature myself, but can make sure to start testing it when changes are made.

**Comment by nadawassef** [comment]
thank you soo much for all your help

**Comment by padster** [comment]
My pleasure! Marking as closed
