### ISSUE TITLE
Text Now White

### ISSUE THREAD

**Issue by Ceej1313** [padster/CalendarThemeExtension#28]
When inputting new event, task, etc - the text to create the title is white (invisible).

How do we fix this?

**Comment by padster** [comment]
Really sorry about that, I accidentally broke it with the last change. A fix has just been submitted, once Google approves it (usually within a day) you'll get updated to the fixed version

**Comment by padster** [comment]
@Ceej1313 Has this since been fixed? Once chrome has updated the extension to version 2.0.11, the title text should be back to visible (in this case, a darker grey)
