### ISSUE TITLE
Create New Calendar Issue

### ISSUE THREAD

**Issue by ciarrocca** [padster/CalendarThemeExtension#3]
Hey! When you go and create a new calendar the text is not showing up. Google is registering it and you're able to make a new calendar with the name you type, you're just not able to see the text in the text box while doing it (same issue with the description box)

**Comment by padster** [comment]
Thanks for reporting! I can confirm that I see it too - i.e. the text is there, but in white, so can't be seen against the background. I can fix that tomorrow, then it'll go live once the Chrome extension folks approve the update (usually a day at most)
