### ISSUE TITLE
Can't change background image, chrome is updated

### ISSUE THREAD

**Issue by nourhanely** [padster/CalendarThemeExtension#5]
I attached a screenshot to what comes up whenever I try to "change" the picture, it has been happening ever since I tried to use the extension. 
![image](https://user-images.githubusercontent.com/76209072/167686176-8896ff6e-9471-45ab-b3a0-6385c9da4420.png)

**Comment by padster** [comment]
Thanks for the screenshot! This bug has been hard to track down, but that helped a lot. I've submitted an update, would you be able to check again in a few days one the upgrade (v 1.0.9) has made it to your chrome? I'm not 100% sure my fix will work as I'm unable to make it look like that myself, but have heard others have seen a similar page.

**Comment by nourhanely** [comment]
IT WORKS! THANK YOU SO SO SO MUCH
