### ISSUE TITLE
Dark Overlay White on White Text

### ISSUE THREAD

**Issue by 300pages** [padster/CalendarThemeExtension#6]
When using the dark overlay, if you are in month view and click on the more for the day to view details the times and events are in white text and are only readable when hovering over each line.
![Annotation 2022-07-21 085956](https://user-images.githubusercontent.com/109740588/180219498-758acf20-26a1-4df6-8e83-8c500fe27c0f.jpg)

**Comment by padster** [comment]
Thanks for reporting! A fix is on the way, it should be updated within a few days

**Comment by padster** [comment]
Hi @300pages, has this been fixed for you? I believe the extension should have updated to the new version for everyone

**Comment by 300pages** [comment]
Yes it fixed! Thanks so much!
