### ISSUE TITLE
Image disappears

### ISSUE THREAD

**Issue by ClazFark** [padster/CalendarThemeExtension#7]
I have found an issue where I put a picture as the background, but after a while, maybe after the page has reloaded a few times, the image dissapears, and I need to get the link and add it again.

**Comment by padster** [comment]
Hi Claz - are you using an image with authentication? Unfortunately some sites have URLs for their images that expire after a certain time; for these images you may have to upload them to a different image provider that supports links that do not expire.

**Comment by ClazFark** [comment]
Thanks for your response. I think that was something to do with it. The way I had done it was that I made a Google Site, put the image on it, and then published the site. Then I would go to the site and right click the image and copy the link. But when it wasn't working, I ended up uploading the image to Pinterest, and copying the link from there instead, and since I changed to that, I haven't had the problem since. Thanks for confirming that the link must expire on certain websites.
