### ISSUE TITLE
Calendar monthly view gridlines interfere with background

### ISSUE THREAD

**Issue by flemesre** [padster/CalendarThemeExtension#8]
As of a few weeks ago, Google Calendar started showing gridlines between the daily cells that interfere with the background, especially dark backgrounds. Was wondering if this is normal/known behaviour and if it can be changed. Thanks!

![image](https://user-images.githubusercontent.com/7189654/197645668-90749059-140f-453b-ab69-69d26d6214ba.png)

**Comment by padster** [comment]
Thanks for the report! I've recently fixed the extension, this should look a lot nicer for you when it updates over the next few days. If you're still having issues, let me know! The lines will still be there, but much more subtle now. Great background picture!

**Comment by flemesre** [comment]
The new lines look great, thank you.

![image](https://user-images.githubusercontent.com/7189654/201207782-1d462553-4d0f-4f52-9314-8853bb886ed6.png)

**Comment by padster** [comment]
hi @flemesre - hopefully this is back to normal with 2.0.4, let me know if it ever appears again!

**Comment by flemesre** [comment]
It is indeed fixed. Thanks!
