### ISSUE TITLE
text will turn white and disappear

### ISSUE THREAD

**Issue by Xeniahhchen** [padster/CalendarThemeExtension#9]
if I choose "Dark overlay", then my google calendar text will turn white and disappear ! It bothers me...
![FireShot Capture 153 - Delivery Hero SE - 日曆 - 2023年5月 - calendar google com](https://user-images.githubusercontent.com/132637453/236376562-7cc9905b-a545-4172-897f-6fba137deda7.jpg)

**Comment by padster** [comment]
Hi Xenia - thanks for reporting this! I recently pushed a fix, hopefully that has made these visible again?
